apiVersion: batch/v1
kind: Job
metadata:
  name: train
spec:
  template:
    spec:
      containers:
      - name: train
        image: tensorflow/tensorflow:latest-gpu-py3
        command: ["ls", "/storage"]
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: $USER-data
