apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: run-notebook
        image: robcurrie/jupyter-gpu
        imagePullPolicy: Always
        # securityContext:
        #   runAsUser: 1000
        env:
          - name: USER
            value: $USER
          - name: AWS_PROFILE
            value: "prp"
          - name: AWS_S3_ENDPOINT
            value: "http://rook-ceph-rgw-rooks3.rook"
          - name: S3_ENDPOINT
            value: "rook-ceph-rgw-rooks3.rook"
          - name: S3_USE_HTTPS
            value: "0"
        volumeMounts:
          - mountPath: /root/.aws
            name: credentials
        resources:
          requests:
            memory: "8Gi"
            nvidia.com/gpu: 0
          limits:
            memory: "8Gi"
            nvidia.com/gpu: 0
        command: ["/bin/bash","-c"]
        args: [
          "
          pwd &&
          ls &&
          aws --endpoint http://rook-ceph-rgw-rooks3.rook s3 ls s3://braingeneers/rcurrie/ &&
          for i in {1..10}; do echo $i && sleep 2; done
          "
        ]

      restartPolicy: Never
      volumes:
      - name: credentials
        secret:
          secretName: s3-credentials
