apiVersion: v1
kind: Pod
metadata:
  name: $USER-pod
spec:
  containers:
  - name: $USER-container
    image: robcurrie/jupyter-gpu
    imagePullPolicy: Always
    env:
      - name: USER
        value: $USER
      # - name: AWS_PROFILE
      #   value: "prp"
      - name: AWS_S3_ENDPOINT
        value: "http://rook-ceph-rgw-rooks3.rook"
      - name: S3_ENDPOINT
        value: "rook-ceph-rgw-rooks3.rook"
      - name: S3_USE_HTTPS
        value: "0"
    args: ["sleep", "infinity"]
    volumeMounts:
      - mountPath: /root/.aws
        name: s3-credentials
    resources:
      requests:
        memory: 8Gi
        hugepages-2Mi: 2Mi
        nvidia.com/gpu: 0
      limits:
        memory: 8Gi
        hugepages-2Mi: 2Mi
        nvidia.com/gpu: 0
  restartPolicy: Never
  volumes:
  - name: s3-credentials
    secret:
      secretName: prp-s3-credentials
